### ISSUE TITLE
Product change race condition

### ISSUE THREAD

**Issue by gizzmojr** [leif81/bzkanban#16]
When I change product and hit submit quickly, I get an alert about unable to connect to site. If I delay pressing Submit for ~1sec it won't pop up. 

I also notice milestone console errors on product changes, I don't know if the same problem is causing it to. 

Both are paper cuts thou.

**Comment by leif81** [comment]
> When I change product and hit submit quickly, I get an alert about unable to connect to site. If I delay pressing Submit for ~1sec it won't pop up.

Ya I'm seeing that too.

It may be a conflict between the form being submitted (which causes the page to reload) and the earlier product change which had issued a `doGet` for `loadMilestonesList` which may not have returned yet. Aborting that `doGet` _may_ be the source of the error.
