### ISSUE TITLE
Drag drop targets missing

### ISSUE THREAD

**Issue by gizzmojr** [leif81/bzkanban#48]
Would appear in 23f293c6f7e0020e6514a467809f59c65c36e83b we lost the ability to drag-n-drop within a column to set priority and severity.

showCards and hideCards will do the work but are no longer being called when the event for dragging a card is fired.

**Comment by leif81** [comment]
Ya the drop targets within the columns all got removed.

The priority and severity can be set now by clicking on a card and changing it in the modal and optionally adding a comment explaining why it changed.

That what you're after?

**Comment by gizzmojr** [comment]
I probably forgot that it was agreed to move more logic into the modal vs DnD stuff. 

It's been awhile since I needed to change the priority/severity so hence my forgetfulness.
Move along, nothing to see here :eyes:
