### ISSUE TITLE
Display limited products for admins

### ISSUE THREAD

**Issue by gizzmojr** [leif81/bzkanban#49]
One issue, being an administrator of a Bugzilla instance, is you always see all products whether valid for input or not.

It be nice to have a feature where I can toggle the ability to only list products that are "is_active: true".

**Comment by leif81** [comment]
Hmm, so I know what you're after. But it would appear we have that behaviour already! Even when logged in with our admin accounts. I think we were assuming this was only the case for regular users or when not logged in. Try it.

**Comment by gizzmojr** [comment]
I see now, we cleaned up the list and now it's just like you said. 

You had used "type=enterable" on the GET so that already filtered out products not open to bug entry.
