### ISSUE TITLE
Spaces in column names not supported

### ISSUE THREAD

**Issue by gizzmojr** [leif81/bzkanban#53]
I did a quick attempt to fix an issue I hit lastnight, moving cards into columns with spaces in names. 

We use the status' as names, and use those as IDs. Kind of a problem once your making class calls and queryselectors with spaces, because it's interpreting "#ONE TWO" as separate things versus one argument. 

The simple fix, is to state as a known_issue that it's unsupported until we rework how to build up the column elements (naming based of returned status')

Or hopefully, some Bugzilla document will state spaces are a no-no, and problem solved? Default status of "IN_PROGRESS" makes me think they might of crossed this issue before.

**Comment by leif81** [comment]
I think the underscore workaround is a reasonable one. Lets _wontfix_ this one.
