### ISSUE TITLE
Gravatar with v6 BZ

### ISSUE THREAD

**Issue by gizzmojr** [leif81/bzkanban#54]
Just realized having switched from 5.0 branch to 5.1.1 tag, that gravatar icons no longer work. 

Latest doc, http://bugzilla.readthedocs.io/en/latest/api/core/v1/bug.html#get-bug, states that "the email address of users is private and is no longer returned as part of the user object."

So that's the problem, bug.assigned_to_detail.email is undefined. 

A suggestion is to create a SET of all people on the board. Doing a GET /user/ID on each, then return their email. 

Problems:
1. Requires the user to be signed in. Read only view will show all the same Gravatar icon, so best hide it all together
2. Doing a GET for each user could be expensive. Do you block the board until it's done, or show the icons after the cards are loaded?

**Comment by leif81** [comment]
It looks like we could reduce the number of GETS by doing a bulk user lookup:

`GET /rest/user?ids=123&ids=321`
