### ISSUE TITLE
Mobile Styling

### ISSUE THREAD

**Issue by gizzmojr** [leif81/bzkanban#55]
There's some downstream projects that use bzkanban, but could benefit from a mobile theme. I don't mean bootstrap stuff, just adjusting modal width and such if resolution less then X, etc

**Comment by gizzmojr** [comment]
Started this on a new branch.
e63e49785d5fea92e2d4b76e457cd4827327f693

Not ready yet for a PR

**Comment by leif81** [comment]
Hope you don't mind I added a commit to your branch.

**Comment by gizzmojr** [comment]
Not at all. In fact, I was stumbling how to get it just right so took a break.
