### ISSUE TITLE
fixed width columns

### ISSUE THREAD

**Issue by captainwasabi** [leif81/bzkanban#68]
Perhaps minimum width instead of fixed width?  Personally, I'd rather them always take the available space.  Some items have long titles and increasing the width of the card means that the titles won't take up so much space. 
The font for the titles seems a little big too.

**Comment by leif81** [comment]
Ya I think `min-width` is an improvement worth keeping. I too am a bit undecided about the `max-width` change. The motivation for that was that I think the board looks a bit silly when there are only 4 or less columns on 1080p monitor. Each column gets stretched so wide. Anyways, I thought I'd try out this new width, other boards like GitHub projects and Trello do a similar thing. If you have other ideas for better ways of handling this let me know. I'll think about it some more too.

**Comment by leif81** [comment]
Btw I agree about the font size. At the time it seemed better. I've just now reverted that part of the change.

**Comment by captainwasabi** [comment]
Maybe have a min-width and a max-width

**Comment by leif81** [comment]
Oh that's what the current implementation is actually.

**Comment by leif81** [comment]
Or do you mean with different values?

**Comment by captainwasabi** [comment]
Yeah, different values.

**Comment by leif81** [comment]
Out of curiousity, what display resolution are you using?

**Comment by captainwasabi** [comment]
Personally I use a variety. 1200x1600 (yes, portrait mode) and 1920x1200.  However I'm rolling this out to more than just myself and that gets into a whole variety of resolutions.  And even just for me, I don't want this to necessarily eat the whole monitor.  I can even see this being used on a projector or 720p large screen (yeah, we still have them to my chagrin) display for meetings.  

You may have noticed from the gist I posted in the other thread that I have some "presets" set up for different departments (kinda), so this lets people (leads&mgmt, programmers, artists, and qa) see the columns they need to see without needing to worry about the rest, then if they want to they can toggle individual columns on and off on top of that.  So it's more like all this is working together and when only a few columns are displayed, only seeing a handful of bugs in the columns (and for any milestone there can be dozens in columns like ASSIGNED) when half the window is empty is less efficient.  

I'm also looking at rolling this out to not only the dev teams I manage, and IT department that I also manage, but also pitching it up to c-levels and corporate admin staff as a company wide paradigm (which will have a very simplified workflow compared to what the product dev team needs).

I've been using Bugzilla for nearly 20 years, and it's not the most user friendly interface for non-technical people.  Your project has me excited to find something that provides that friendliness.  I've been using it for a Kanban-like process for 5-6 years already. I've been looking for this for a long time, and since both GitHub and GitLab have come out with solutions, I expected to see something like this popping up soon.

**Comment by leif81** [comment]
Cool thanks for the background info. Your history and environment sounds somewhat similiar to mine.

I'm still a bit undecided which is the best direction to go. Stretched columns seem not ideal, but neither does the wasted space. I also tried out centering the board. You can try it by setting `align-self: center` on the `#board` element.
