### ISSUE TITLE
A board is not displayed in the Edge browser

### ISSUE THREAD

**Issue by Alexcei88** [leif81/bzkanban#72]
I am trying to open [this kanban board](https://rawgit.com/leif81/bzkanban/master/index.html?product=Bugzilla&milestone=Bugzilla+6.0&assignee=&comments=false&site=https%3A%2F%2Fbugzilla.mozilla.org) in the Edge browser.  The board is not displayed.
In the yandex browser this board is displayed correct.

**Comment by leif81** [comment]
Hi @Alexcei88 thanks for the report. 

I hadn't tried bzkanban with Edge before. But I see the same issue you having.

I've been developing and testing with Chrome up until now.

**Comment by leif81** [comment]
I've made some progress and pushed a couple changes. The board will load in Edge, with some issues, if the URL contains a value for the `milestone` parameter.

e.g.

https://rawgit.com/leif81/bzkanban/master/index.html?product=Bugzilla&milestone=Bugzilla%206.0&assignee=&comments=false&autorefresh=false&site=https://bugzilla.mozilla.org

But the overall experience in Edge is still really bad. It's very slow, the milestone can't be changed, the cursor sometimes doesn't update, and the board seems to be trying to load itself multiple times, possibly the cause of the slowness.

**Comment by leif81** [comment]
Ok all the slowless was related to the board loading over and over. Our event handlers for the product and milestone `<select>` lists were firing repeatedly during page load in MS Edge, which is unexpected. They should only be firing when the user changes the value in those lists, to prompt a board re-load.

This should fix the issue with Edge. The board should load and performance is good too.

**Comment by Alexcei88** [comment]
Thanks. The board is displayed in the Edge browser now.
