### ISSUE TITLE
Connecting to Bugzilla with login cause several popups

### ISSUE THREAD

**Issue by kjp023** [leif81/bzkanban#80]
First I would like to say that this board is a very nice graphical front end to Bugzilla! Good work!

When loading Bz Kanban Board connected to a Bugzilla site using login you get several "You must log in before using this part of Bugzilla." pop up messages. These prevent pressing anything on the web page including the login button and force you to acknowledge this several times before being able to press the login button. I guess this is caused by the initBoard() function doing async.parallel() call to fetch several different data before a successful login attempt is made.

I have also noticed that sometimes also after pressing the login button I get more of these pop ups. Something is evidently trying to fetch data while not logged in. One possible solution might be to try to determine if login is needed, if so don't fetch any data. Once logged in (or no login needed) data can be fetched.

**Comment by leif81** [comment]
Thank-you for the report @kjp023 . I'll give this some thought.

**Comment by leif81** [comment]
I've pushed a branch that may address your issue. @kjp023 can you try it and let me know?

**Comment by leif81** [comment]
From the testing I've done this appears to fix your issue @kjp023 . I've merged this change into master. Please reopen if you have any problems.

**Comment by kjp023** [comment]
Hi,
Sorry for slow feedback but this appears to work fine now! Thanks for great support!
