### ISSUE TITLE
Automatic user login in same origin

### ISSUE THREAD

**Issue by glance-** [leif81/bzkanban#83]
We use external env authentication for our bugzilla, to auth it against our other auth infrastructure. That means user can't login to rest via username / password.

I've seen the patches to use api keys, but I'd rather run bzkanban in the same origin as bugzilla and just automatically login the user.

I've dug around in bugzilla but I can't figure out any sane way of doing this, so that's why I'm asking you guys. Is there any way to implement such a functionallity?

**Comment by leif81** [comment]
@glance- I'm not familiar with auto login for web apps. bzkanban depends on the authentication system provided by Bugzilla. You may have found it already, here are the Bugzilla docs on user authentication: 
https://bugzilla.readthedocs.io/en/5.0.4/administering/parameters.html#user-authentication

**Comment by glance-** [comment]
OK. This was the way I solved it. Writing  this one up for anyone else that might be interested in what I figured out.

I used https://github.com/zmartzone/mod_auth_openidc to setup oauth for our bugzilla, and made it mandatory for our bzkanban path's but made it optional for our rest-api paths.

Then, I configured mod_auth_openidc with SameSite cookie policy as Strict and hacked out the disablement of auth_no_automatic_login in the rest api.

This way the SameSite cookie policy ensures no cross site scripting can get access to the cookies and abuse the rest api. Also by not making oauth mandatory for the rest-path, I still kept support for API-keys, but enabled auto-login in bzkanban.


Then I did some really dirty hacking in bzkanban to have it in "logged-in"-mode. Maybe this part might be interesting for some one else in the future, so I'll fork this and push my dirty patch there for anyone interested.

**Comment by leif81** [comment]
Thanks for sharing @glance- 

Yes, I'd be interested in seeing your forked change required for this.

**Comment by glance-** [comment]
It's no rocket-surgery, so I published it as:
https://github.com/glance-/bzkanban/commit/686dd5dd566bd03468236279dea27f6f7755c4eb

That and defaulting siteUrl to window.location.origin:
https://github.com/glance-/bzkanban/commit/7ee7c02f3233640fef775eef7b7602dbbf2a39c8

That together with the following in bugzilla:
```diff --git a/Bugzilla/WebService/Server/REST.pm b/Bugzilla/WebService/Server/REST.pm
index 143b938b6..b1b3e5e43 100644
--- a/Bugzilla/WebService/Server/REST.pm
+++ b/Bugzilla/WebService/Server/REST.pm
@@ -200,7 +200,13 @@ sub handle_login {
     # to Bugzilla->login at this point, so we pass this information
     # around using request_cache, which is a bit of a hack. The
     # implementation of it is in Bugzilla::Auth::Login::Stack.
-    Bugzilla->request_cache->{'auth_no_automatic_login'} = 1;
+    #
+    # We have SameSite Strict in the cookies, so this doesn't apply.
+    # When using oauth, we don't get the normal Bugzill cookies
+    # which can be (ab)used for cross site things.
+    #
+    # This way we can get automatic login in bzkanban
+    #Bugzilla->request_cache->{'auth_no_automatic_login'} = 1;
   }
 
   my $class       = $self->bz_class_name;
```
